
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 17 23:41:59 CET 2013
//----------------------------------------------------

package pl.edu.pjwstk.chemcalc.code.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int OP = 3;
  public static final int RIGHT_BRACKET = 7;
  public static final int ELEMENT_EXPRESSION = 5;
  public static final int INTEGER_LITERAL = 4;
  public static final int error = 1;
  public static final int LEFT_BRACKET = 6;
  public static final int LOW_INDEX = 2;
  public static final int EOF = 0;
}

